# Generated by Django 5.1.6 on 2025-02-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoeiya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='cinema',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Filmlar'},
        ),
    ]
