# Generated by Django 5.1.6 on 2025-02-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_category_options_alter_cinema_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
