# Generated by Django 5.1.6 on 2025-02-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_rename_created_ad_cinema_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ssilka video'),
        ),
    ]
